### ISSUE TITLE
Possible problem in compute encryption of c2

### ISSUE THREAD

**Issue by lucasjoao** [debjitbis08/elgamal-demo#3]
I think that the calculation of c2 has a problem (missing a "mod p"), because if you do this:

> Say the receiver chooses prime p = 71, and g=33 (one can check that 33 is a generator of {\mathbb Z}_{71}^*), and secret exponent x=62. Then h = g^x \bmod 71 = 10. (I won’t explicitly write the “\bmod 71” anymore.) The receiver would publish the public key (p=71, g=33, h=10).
Say a sender wants to send the message m=15. It chooses random exponent r=31, say, computes the ciphertext (g^r, h^rm) = (62, 18), and sends this to the receiver.

From the [reference](https://cmsc414.wordpress.com/2009/09/23/el-gamal-examples/) the result will be 870, but in the site, and if you make the calculation, the result should be 18.

I believe that the right formula is **c2 = ((h^r mod p) * m) mod p**.

**Comment by debjitbis08** [comment]
@lucasjoao, Yes you are correct, will fix this.

**Comment by debjitbis08** [comment]
Fixed and deployed.
